# config/database.yml

default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: mysite_i0d9
  username: mysite_i0d9_user
  password: <%= ENV['MYSITE_DATABASE_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>
