# config/database.yml

# 共通設定 anchor
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: db/development.sqlite3

development:
  <<: *default

# テスト用
test:
  <<: *default
  database: db/test.sqlite3

# Production (固定値)
production:
  primary: &primary_production
    adapter: postgresql
    encoding: unicode
    pool: 5
    database: mysite_i0d9
    username: mysite_i0d9_user
    password: <%= ENV['MYSITE_DATABASE_PASSWORD'] %>
    url: <%= ENV['DATABASE_URL'] %>

  cache:
    <<: *primary_production
  queue:
    <<: *primary_production
  cable:
    <<: *primary_production
